---
- name: 3proxy
  comment: Proxy server which supports HTTP(S), FTP, SOCKS, POP3, TCP & UDP
  url: http://3proxy.ru/
  donations: http://3proxy.ru/donations/
  methods:
    - bank_transfer
    - bitcoin
    - cheque
    - webmoney
    - western_union
  detection:
    pkgnames:
      - 3proxy

- name: Blender
  comment: 3D modeling/rendering/animation/gaming package
  url: http://www.blender.org/
  donations: http://www.blender.org/foundation/donation-payment/
  methods:
    - paypal
    - bitcoin
    - bank_transfer
  detection:
    pkgnames:
      - blender

- name: Doxygen
  comment: 3D modeling/rendering/animation/gaming package
  url: http://doxygen.org/
  methods:
    - paypal
  detection:
    pkgnames:
      - doxygen

- name: GIMP
  comment: GNU Image Manipulation Program
  url: http://www.gimp.org/
  donations: http://www.gimp.org/donating/
  methods:
    - paypal
    - flattr
    - bitcoin
    - bank_transfer
    - cheque
  detection:
    pkgnames:
      - gimp
      - gimp-app

- name: GnuPG
  comment: GNU privacy guard - a free PGP replacement
  url: https://www.gnupg.org/
  donations: https://www.gnupg.org/donate/index.html
  methods:
    - credit_card
    - paypal
  detection:
    pkgnames:
      - gnupg
      - gnupg1
      - gnupg2

- name: GPSd
  comment: GPS service daemon
  url: http://www.catb.org/gpsd/
  methods:
    - patreon
  detection:
    pkgnames:
      - gpsd

- name: MariaDB
  comment: Multithreaded SQL database from developers of MySQL
  url: https://mariadb.org/
  donations: https://mariadb.org/donate/
  methods:
    - bank_transfer
    - flattr
    - paypal
  detection:
    pkgnames:
      - mariadb-server
      - mariadb55-server
      - mariadb100-server
      - mariadb101-server

- name: MPlayer
  comment: High performance media player supporting many formats
  url: https://www.mplayerhq.hu/
  donations: https://www.mplayerhq.hu/design7/donations.html
  methods:
    - paypal
    - flattr
    - hardware
  detection:
    pkgnames:
      - mplayer
      - mencoder

- name: MuseScore
  comment: Free music composition and notation software
  url: https://musescore.org/
  donations: https://musescore.org/en/donate
  methods:
    - credit_card
    - paypal
    - bank_transfer
    - patreon
    - bitcoin
    - tibit
    - merchandise
  detection:
    pkgnames:
      - musescore

- name: Python
  comment: Interactive high-level object-oriented language
  url: https://www.python.org/
  donations: https://www.python.org/psf/donations/
  methods:
    - bank_transfer
    - cheque
    - credit_card
    - paypal
  detection:
    pkgnames:
      - python
      - python2
      - python3

- name: Sweet Home 3D
  comment: Free interior design application
  url: http://www.sweethome3d.com/
  donations: http://www.sweethome3d.com/donate.jsp
  methods:
    - paypal
  detection:
    pkgnames:
      - sweethome3d

- name: Tiled
  comment: Free, easy to use and flexible tile map editor
  url: http://www.mapeditor.org/
  donations: http://www.mapeditor.org/donate.html
  methods:
    - bank_transfer
    - bountysource
    - patreon
    - paypal
  detection:
    pkgnames:
      - tiled

- name: Tor Project
  comment: Anonymizing overlay network for TCP
  url: https://www.torproject.org/
  donations: https://www.torproject.org/donate/donate-options.html.en
  methods:
    - amazon
    - bank_transfer
    - bitcoin
    - cheque
    - dwolla
    - paypal
  detection:
    pkgnames:
      - tor
