- name: 0 A.D.
  description: Real-time strategy game of ancient warfare
  url: https://play0ad.com/
  donations: https://play0ad.com/community/donate/
  methods:
    - paypal
    - clickandpledge
    - flattr
  detection:
    pkgnames:
      - 0ad

- name: Blender
  comment: 3D modeling/rendering/animation/gaming package
  url: http://www.blender.org/
  donations: http://www.blender.org/foundation/donation-payment/
  methods:
    - paypal
    - bitcoin
    - bank_transfer
  detection:
    pkgnames:
      - blender

- name: INSTEAD
  comment: Simple text adventures/visual novels engine
  url: http://instead.syscall.ru/
  donations: http://instead.syscall.ru/donate/
  methods:
    - yandex_money
  detection:
    pkgnames:
      - instead
