- name: Blender
  comment: 3D modeling/rendering/animation/gaming package
  url: http://www.blender.org/
  donations: http://www.blender.org/foundation/donation-payment/
  methods:
    - paypal
    - bitcoin
    - bank_transfer
  detection:
    pkgnames:
      - blender

- name: INSTEAD
  comment: Simple text adventures/visual novels engine
  url: http://instead.syscall.ru/
  donations: http://instead.syscall.ru/donate/
  methods:
    - yandex-money
  detection:
    pkgnames:
      - instead
