---
- name: 3proxy
  comment: Proxy server which supports HTTP(S), FTP, SOCKS, POP3, TCP & UDP
  url: http://3proxy.ru/
  donations: http://3proxy.ru/donations/
  methods:
    - bank_transfer
    - bitcoin
    - cheque
    - webmoney
    - western_union
  detection:
    pkgnames:
      - 3proxy
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Audacity
  comment: Cross-platform software for recording and editing sounds
  url: http://www.audacityteam.org/
  donations: http://www.audacityteam.org/donate/
  methods:
    - paypal
  detection:
    pkgnames:
      - audacity
  added: 2016-04-20
  last_checked: 2016-04-20

- name: BitlBee
  comment: IRC to other chat networks gateway
  url: https://bitlbee.org/
  methods:
    - paypal
    - bitcoin
  detection:
    pkgnames:
      - bitlbee
  added: 2016-05-16
  last_checked: 2016-05-16

- name: Blender
  comment: 3D modeling/rendering/animation/gaming package
  url: http://www.blender.org/
  donations: http://www.blender.org/foundation/donation-payment/
  methods:
    - paypal
    - bitcoin
    - bank_transfer
  detection:
    pkgnames:
      - blender
  added: 2016-04-18
  last_checked: 2016-04-18

- name: Code::Blocks
  comment: Open source, cross platform, free C, C++ and Fortran IDE
  url: http://www.codeblocks.org/
  donations: http://www.codeblocks.org/donations
  methods:
    - paypal # sourceforge button
  detection:
    pkgnames:
      - codeblocks
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Claws Mail
  comment: User-friendly, lightweight, and fast email client
  url: http://www.claws-mail.org/
  donations: http://www.claws-mail.org/sponsors.php?section=community
  methods:
    - bitcoin
    - dash
    - merchandise
    - paypal
  detection:
    pkgnames:
      - claws-mail
  added: 2016-05-10
  last_checked: 2016-05-10

- name: Doxygen
  comment: 3D modeling/rendering/animation/gaming package
  url: http://doxygen.org/
  methods:
    - paypal
  detection:
    pkgnames:
      - doxygen
  added: 2016-04-19
  last_checked: 2016-04-19

- name: Enlightenment
  comment: Artistic X window manager
  url: https://www.enlightenment.org/
  donations: https://www.enlightenment.org/contribute
  location: France
  methods:
    - paypal
    - flattr
  detection:
    pkgnames:
      - enlightment
      - e17
      - e16
  added: 2016-05-12
  last_checked: 2016-05-12

- name: GIMP
  comment: GNU Image Manipulation Program
  url: http://www.gimp.org/
  donations: http://www.gimp.org/donating/
  methods:
    - paypal
    - flattr
    - bitcoin
    - bank_transfer
    - cheque
  detection:
    pkgnames:
      - gimp
      - gimp-app
  added: 2016-04-19
  last_checked: 2016-04-19

- name: GNU Octave
  comment: High-level interactive language for numerical computations
  url: https://www.gnu.org/software/octave/
  donations: https://www.gnu.org/software/octave/donate.html
  methods:
    - bitcoin
  detection:
    pkgnames:
      - octave
  added: 2016-05-10
  last_checked: 2016-05-10

- name: GnuPG
  comment: GNU privacy guard - a free PGP replacement
  url: https://www.gnupg.org/
  donations: https://www.gnupg.org/donate/index.html
  methods:
    - credit_card
    - paypal
  detection:
    pkgnames:
      - gnupg
      - gnupg1
      - gnupg2
      - gnupg20
  added: 2016-04-19
  last_checked: 2016-04-19

- name: GPSd
  comment: GPS service daemon
  url: http://www.catb.org/gpsd/
  methods:
    - patreon
  detection:
    pkgnames:
      - gpsd
  added: 2016-04-20
  last_checked: 2016-04-20

- name: GPSBabel
  comment: GPS file translating tool
  url: http://www.gpsbabel.org/
  methods:
    - paypal
  detection:
    pkgnames:
      - gpsbabel
      - gpsbabel14
  added: 2016-05-16
  last_checked: 2016-05-16

- name: HAProxy
  comment: Reliable, High Performance TCP/HTTP Load Balancer
  url: http://www.haproxy.org/
  methods:
    - paypal
  detection:
    pkgnames:
      - haproxy
  added: 2016-05-12
  last_checked: 2016-05-12

- name: Hugin
  comment: Panorama photo stitcher
  url: http://hugin.sourceforge.net/
  methods:
    - paypal # sourceforge button
  detection:
    pkgnames:
      - hugin
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Inkscape
  comment: Professional cross-platform vector graphics editor
  url: https://inkscape.org/
  donations: https://inkscape.org/support-us/donate/
  methods:
    - paypal
    - cheque
  detection:
    pkgnames:
      - inkscape
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Lazarus
  comment: Delphi compatible cross-platform IDE for Rapid Application Development
  url: http://www.lazarus-ide.org/
  donations: http://wiki.lazarus.freepascal.org/How_to_donate_to_Lazarus
  methods:
    - paypal
  detection:
    pkgnames:
      - lazarus
  added: 2016-05-16
  last_checked: 2016-05-16

- name: LeechCraft
  comment: Cross-platform modular live environment
  url: https://leechcraft.org/
  donations: https://leechcraft.org/donate
  methods:
    - paypal
    - yandex_money
  detection:
    pkgnames:
      - leechcraft
  added: 2016-05-11
  last_checked: 2016-05-11

- name: LFTP
  comment: Sophisticated command line ftp/http client
  url: https://lftp.yar.ru/
  donations: https://lftp.yar.ru/contribute.html
  methods:
    - paypal
    - webmoney
    - flattr
  detection:
    pkgnames:
      - lftp
  added: 2016-05-11
  last_checked: 2016-05-11

- name: LibreOffice
  comment: Full integrated office productivity suite
  url: https://www.libreoffice.org/
  donations: https://www.libreoffice.org/donate/
  methods:
    - bank_transfer
    - bitcoin
    - flattr
    - paypal
  detection:
    pkgnames:
      - libreoffice
      - libreoffice4
      - libreoffice5
  added: 2016-04-20
  last_checked: 2016-04-20

- name: MariaDB
  comment: Multithreaded SQL database from developers of MySQL
  url: https://mariadb.org/
  donations: https://mariadb.org/donate/
  methods:
    - bank_transfer
    - flattr
    - paypal
  detection:
    pkgnames: # XXX: needs periodical recheck
      - mariadb-server
      - mariadb55-server
      - mariadb100-server
      - mariadb101-server
  added: 2016-04-20
  last_checked: 2016-04-20

- name: mcabber
  comment: Small XMPP (Jabber) console client
  url: http://mcabber.com/
  methods:
    - paypal
  detection:
    pkgnames:
      - mcabber
  added: 2016-05-10
  last_checked: 2016-05-10

- name: MPlayer
  comment: High performance media player supporting many formats
  url: https://www.mplayerhq.hu/
  donations: https://www.mplayerhq.hu/design7/donations.html
  methods:
    - paypal
    - flattr
    - hardware
  detection:
    pkgnames:
      - mplayer
      - mencoder
  added: 2016-04-19
  last_checked: 2016-04-19

- name: MuseScore
  comment: Free music composition and notation software
  url: https://musescore.org/
  donations: https://musescore.org/en/donate
  methods:
    - credit_card
    - paypal
    - bank_transfer
    - patreon
    - bitcoin
    - tibit
    - merchandise
  detection:
    pkgnames:
      - musescore
  added: 2016-04-20
  last_checked: 2016-04-20

- name: PostgreSQL
  comment: World's most advanced open source database
  url: http://www.postgresql.org/
  donations: http://www.postgresql.org/about/donate/
  methods:
    - paypal
    - bank_transfer
  detection:
    pkgnames: # XXX: needs periodical recheck
      - postgresql90-server
      - postgresql91-server
      - postgresql92-server
      - postgresql93-server
      - postgresql94-server
      - postgresql95-server
      - postgresql
      - postgresql-9.4
      - postgresql-server
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Python
  comment: Interactive high-level object-oriented language
  url: https://www.python.org/
  donations: https://www.python.org/psf/donations/
  methods:
    - bank_transfer
    - cheque
    - credit_card
    - paypal
  detection:
    pkgnames: # XXX: needs periodical recheck
      - python
      - python2
      - python27
      - python3
      - python33
      - python34
      - python35
  added: 2016-04-19
  last_checked: 2016-04-19

- name: QGIS
  comment: Free and Open Source Geographic Information System
  url: http://www.qgis.org/
  donations: http://www.qgis.org/en/site/getinvolved/donations.html
  methods:
    - paypal
    - bank_transfer
  detection:
    pkgnames:
      - qgis
  added: 2016-05-12
  last_checked: 2016-05-12

- name: QuiteRSS
  comment: Open-source cross-platform RSS/Atom news feeds reader
  url: http://quiterss.org/
  donations: http://quiterss.org/donations
  methods:
    - paypal
    - yandex_money
    - webmoney # wmr
  detection:
    pkgnames:
      - quiterss
  added: 2016-05-12
  last_checked: 2016-05-12

- name: rdesktop
  comment: UNIX client for connecting to Windows Remote Desktop Services
  url: http://www.rdesktop.org/
  methods:
    - bountysource
  detection:
    pkgnames:
      - rdesktop
  added: 2016-05-16
  last_checked: 2016-05-16

- name: Samba
  comment: Standard Windows interoperability suite of programs for Linux and Unix
  url: https://www.samba.org/
  donations: https://www.samba.org/samba/donations.html
  methods:
    - cheque
    - paypal
  detection:
    pkgnames: # XXX: needs periodical recheck
      - samba
      - samba36
      - samba41
      - samba42
      - samba43
  added: 2016-04-22
  last_checked: 2016-04-22

- name: SMPlayer # XXX: auto-include mplayer
  comment: Graphical user interface for MPlayer
  url: http://smplayer.sourceforge.net/
  donations: http://smplayer.sourceforge.net/en/contribute
  methods:
    - paypal
    - bitcoin
  detection:
    pkgnames:
      - smplayer
  added: 2016-05-10
  last_checked: 2016-05-10

- name: Stellarium
  comment: Free open source planetarium for your computer
  url: http://www.stellarium.org/
  methods:
    - paypal # sourceforge button
  detection:
    pkgnames:
      - stellarium
      - stellarium-qt4
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Sweet Home 3D
  comment: Free interior design application
  url: http://www.sweethome3d.com/
  donations: http://www.sweethome3d.com/donate.jsp
  methods:
    - paypal
  detection:
    pkgnames:
      - sweethome3d
  added: 2016-04-20
  last_checked: 2016-04-20

- name: Tiled
  comment: Free, easy to use and flexible tile map editor
  url: http://www.mapeditor.org/
  donations: http://www.mapeditor.org/donate.html
  methods:
    - bank_transfer
    - bountysource
    - patreon
    - paypal
  detection:
    pkgnames:
      - tiled
  added: 2016-04-19
  last_checked: 2016-04-19

- name: Tor Project
  comment: Anonymizing overlay network for TCP
  url: https://www.torproject.org/
  donations: https://www.torproject.org/donate/donate-options.html.en
  methods:
    - amazon
    - bank_transfer
    - bitcoin
    - cheque
    - dwolla
    - paypal
  detection:
    pkgnames:
      - tor
      - tor-devel
      - obfsproxy
  added: 2016-04-19
  last_checked: 2016-04-19

- name: Transmission
  comment: Fast, easy and free BitTorrent client
  url: https://www.transmissionbt.com/
  donations: https://www.transmissionbt.com/donate.php
  methods:
    - paypal
  detection:
    pkgnames:
      - transmission
      - transmission-cli
      - transmission-daemon
      - transmission-gtk
      - transmission-qt4
      - transmission-remote-gui
      - transmission-web
  added: 2016-04-22
  last_checked: 2016-04-22

- name: TuxGuitar
  comment: Open source tablature editor
  url: http://www.tuxguitar.com.ar/
  donations: http://www.tuxguitar.com.ar/donate.html
  methods:
    - cheque
    - paypal
  detection:
    pkgnames:
      - tuxguitar
  added: 2016-04-20
  last_checked: 2016-04-20

- name: uTox
  comment: Lightweight Tox client
  url: http://utox.org/
  donations: http://utox.org/donate.html
  methods:
    - paypal
    - bitcoin
  detection:
    pkgnames:
      - uTox
      - utox
  added: 2016-05-16
  last_checked: 2016-05-16

- name: vsftpd
  comment: Secure and fast FTP server for UNIX-like systems
  url: https://security.appspot.com/vsftpd.html
  methods:
    - paypal
  detection:
    pkgnames:
      - vsftpd
  added: 2016-05-10
  last_checked: 2016-05-10

- name: WCM Commander
  comment: Multi-platform open source file manager
  url: http://wcm.linderdaum.com/
  methods:
    - paypal
  detection:
    pkgnames:
      - wcmcommander
  added: 2016-04-25
  last_checked: 2016-04-25

- name: Wine
  comment: Compatibility layer capable of running Windows applications
  url: https://www.winehq.org/
  donations: https://www.winehq.org/donate
  methods:
    - paypal
    - merchandise
    - cheque
  detection:
    pkgnames:
      - wine
      - wine-devel
      - wine-staging
      - i386-wine # FreeBSD: wine for amd64
      - i386-wine-devel
      - i386-wine-staging
  added: 2016-04-20
  last_checked: 2016-04-20
