---
- name: Blender
  comment: 3D modeling/rendering/animation/gaming package
  url: http://www.blender.org/
  donations: http://www.blender.org/foundation/donation-payment/
  methods:
    - paypal
    - bitcoin
    - bank_transfer
  detection:
    pkgnames:
      - blender

- name: GIMP
  comment: GNU Image Manipulation Program
  url: http://www.gimp.org/
  donations: http://www.gimp.org/donating/
  methods:
    - paypal
    - flattr
    - bitcoin
    - bank_transfer
    - cheque
  detection:
    pkgnames:
      - gimp
      - gimp-app

- name: Tiled
  comment: Free, easy to use and flexible tile map editor
  url: http://www.mapeditor.org/
  donations: http://www.mapeditor.org/donate.html
  methods:
    - bank_transfer
    - bountysource
    - patreon
    - paypal
  detection:
    pkgnames:
      - tiled
