---
type: map
mapping:
  "version":
    required: true
    type: str
    pattern: /^\d+\.\d+\.\d+$/
  "methods":
    required: true
    type: seq
    sequence:
      - unique: true
        type: str
        pattern: /.*\.yml$/
  "projects":
    required: true
    type: seq
    sequence:
      - unique: true
        type: str
        pattern: /.*\.yml$/
